### ISSUE TITLE
Tracking issue for Kubewarden docs' Docusaurus transition

### ISSUE THREAD

**Issue by divya-mohan0209** [kubewarden/docs#101]
### Is your feature request related to a problem?

Following tasks to be accomplished for Docusaurus migration

- [x]  Set up contact with UI/UX team for understanding template colours
- [x] Create a dev-docusaurus branch for staging the content on local GitHub repo
- [x] Seek assistance for CSS & fonts
- [X] Demonstration of revised content
- [X] Creation of staging/preview branch in the docs repo
- [X] Final demo before go-live

### Solution you'd like

This is an issue to track the progress of docusaurus migration for Kubewarden.
