### ISSUE TITLE
Documentation improvements as per CNCF recommendations

### ISSUE THREAD

**Issue by jhkrug** [kubewarden/docs#477]
CNCF recommendations report is [here](https://docs.google.com/document/d/1shAoi7TJOtuW8z6heR_sUhv3uE7Gk6k6argd_zffaZk/edit?tab=t.0): 

This issue lays out the needed/suggested tasks:

## Specific

- [ ] Documentation layout description page
- [ ] Provide a page with a description of personas using and developing Kubewarden, at whom the documentation is aimed.
  - Provide a map/list of pages relevant to each persona. Continues/extends work began in #400 and #425.
  - Each page should have a statement regarding the personas the page is aimed at?
  - For each persona provide: their likely experience, Kubernetes knowledge, goals in using the docs, expected learnings.
- [ ] Kubewarden what is/introduction page review
  - New user section. If you are new to KW ... blah, blah. 
  - Core features and benefits. What problem(s) does KW solve? The value proposition?
  - Link to and review/improve the explanation/architecture (referred to as the 'Overview' in the CNCF critique) page
  - Provide a recent developments and future roadmap section. Possibly point to an additional page.
- [ ] Quick start page review
  - Link to the improved architecture document to provide context
  - Where can KW be installed? On prem? Cloud? Well, it's really wherever your K8s clusters are
  - Helm charts and their role in installation. More context and links to further information
  - Better description of prerequisites and their configuration
  - Common issues and errors
  - Validate copy/paste installation of basic installation on basic K8S. How deep to go?
  - Review main components section
  - Format and legal value for attributes table.
  - Further worked examples for differing scenarios?
- [ ] New main docs section 'Policy management (& development)'?
  - Management
  - Development tutorials (Rust, etc.)

## General

- [ ] Review for active voice
- [ ] Style guide consistency, currently Microsoft(y), but SUSE docs have their own style guide. Which is quite different.
